"""esquema inicial

Revision ID: c08feca0ce74
Revises: 
Create Date: 2026-07-30 20:24:35.524604

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'c08feca0ce74'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('banco', sa.String(length=32), nullable=False),
    sa.Column('cantidad_filas', sa.Integer(), nullable=False),
    sa.Column('cantidad_transferencias', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transferencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('banco', sa.String(length=32), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cuit', sa.String(length=11), nullable=True),
    sa.Column('importe', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('huella', sa.String(length=64), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=True),
    sa.Column('domicilio', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=16), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('huella', name='uq_transferencias_huella')
    )
    op.create_index(op.f('ix_transferencias_cuit'), 'transferencias', ['cuit'], unique=False)
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transferencia_id', sa.Integer(), nullable=False),
    sa.Column('cuit_receptor', sa.String(length=11), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=True),
    sa.Column('domicilio', sa.String(length=255), nullable=True),
    sa.Column('concepto_descripcion', sa.String(length=255), nullable=False),
    sa.Column('tipo_comprobante', sa.Integer(), nullable=False),
    sa.Column('punto_venta', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('importe', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha_comprobante', sa.Date(), nullable=False),
    sa.Column('cae', sa.String(length=32), nullable=True),
    sa.Column('cae_vencimiento', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=16), nullable=False),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['transferencia_id'], ['transferencias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transferencia_id', name='uq_facturas_transferencia')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facturas')
    op.drop_index(op.f('ix_transferencias_cuit'), table_name='transferencias')
    op.drop_table('transferencias')
    op.drop_table('lotes')
    # ### end Alembic commands ###
